### ISSUE TITLE
Xcode7.3很容易插件崩溃

### ISSUE THREAD

**Issue by leiyantianji** [keepyounger/HighlightSelectedString#17]
哎，在某些原因下，我“需要”升级Xcode。结果Xcode显示因为这插件崩溃，很容易出现。现在用习惯了，感觉不用这插件，Xcode都废了。大神速速来拯救我吧。

**Comment by leiyantianji** [comment]
崩溃日志显示
- (void)symbolsOnlyClick
  {
  self.symbolsOnlyMenuItem.state = !self.symbolsOnlyMenuItem.state;
  
  if (!self.symbolsOnlyMenuItem.state) {
      self.doubleClickMenuItem.action = NULL;
  } else{
      self.doubleClickMenuItem.action = @selector(doubleClick);
  }
  
  [self resetHighlight];
  
  NSUserDefaults *userD = [NSUserDefaults standardUserDefaults];
  [userD setObject:@(self.symbolsOnlyMenuItem.state) forKey:HighlightOnlySymbolsKey];
  [userD synchronize];
  }
  这一行self.doubleClickMenuItem.action = @selector(doubleClick);

**Comment by keepyounger** [comment]
我这边没有这个问题，你确定是这个插件引起的？有时候XCode会误报，能把具体错误信息贴上来吗？就是XCode崩溃的时候，有个弹窗说XCode崩溃了，那里面包含具体的错误信息。谢谢！

**Comment by keepyounger** [comment]
还有你崩溃时你的操作步骤。

**Comment by leiyantianji** [comment]
稍等，今天崩的次数太多了。为了不影响正常工作已经卸载了。现在装上，明天应该能收集到信息。哈哈，多谢啦

**Comment by leiyantianji** [comment]
在使用一个.m时未导入相关头文件，然后崩了
![2016-03-25 09 26 44](https://cloud.githubusercontent.com/assets/12756236/14035667/b9ebe7d2-f26b-11e5-9865-1c8ff949a2e3.png)
Process:               Xcode [442]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.3 (10183.3)
Build Info:            IDEFrameworks-10183003000000000~2
App Item ID:           497799835
App External ID:       816750016
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [442]
User ID:               501

PlugIn Path:             /Users/USER/Library/Application Support/Developer/*/HighlightSelectedString
PlugIn Identifier:       com.lixy.HighlightSelectedString
PlugIn Version:          2.1.1 (1)

Date/Time:             2016-03-25 09:24:00.667 +0800
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        B6F5734F-5CBB-74E1-3331-9289A348D1B3

Time Awake Since Boot: 1700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000006e00610098
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x6e00610098:
    mapped file            0000000187afc000-000000018827b000 [ 7676K] rw-/rwx SM=COW  
--> 
    JS JIT generated code  0000477babc00000-0000477babc01000 [    4K] ---/rwx SM=NUL  

Application Specific Information:
NSTextViewDidChangeSelectionNotification
Sending _issueMenuAction: to <IDEEditorIssueMenuController: 0x7fcd3e1e19c0> from <NSMenuItem: 0x7fcd272c1470 No visible @interface for 'NewlandEptokInterface' declares the selector 'initWithGetTimeBlock:showPWKeyboard:'>
ProductBuildVersion: 7D175
Performing @selector(_issueMenuAction:) from sender NSMenuItem 0x7fcd272c1470
closed document

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib                 0x00007fff9ef5bec1 objc_retain + 33
1   com.lixy.HighlightSelectedString    0x000000011341250e -[HighlightSelectedString selectionDidChange:] + 155 (HighlightSelectedString.m:245)
2   com.apple.CoreFoundation        0x00007fff8f27bbbc **CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER** + 12
3   com.apple.CoreFoundation        0x00007fff8f27bb4f ___CFXRegistrationPost_block_invoke + 63
4   com.apple.CoreFoundation        0x00007fff8f27bac7 _CFXRegistrationPost + 407
5   com.apple.CoreFoundation        0x00007fff8f27b832 ___CFXNotificationPost_block_invoke + 50
6   com.apple.CoreFoundation        0x00007fff8f2385e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
7   com.apple.CoreFoundation        0x00007fff8f237835 _CFXNotificationPost + 693
8   com.apple.Foundation            0x00007fff8c876fda -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
9   com.apple.dt.DVTFoundation      0x00000001055120ef -[NSNotificationCenter(DVTNSNotificationCenterAdditions) _dvt_postNotificationName:object:userInfo:] + 831
10  com.apple.AppKit                0x00007fff99272d18 -[NSTextView(NSSharing) setSelectedRanges:affinity:stillSelecting:] + 7403
11  com.apple.dt.DVTKit             0x0000000105c87e23 -[DVTCompletingTextView setSelectedRanges:affinity:stillSelecting:] + 201
12  com.apple.dt.DVTKit             0x0000000105bbcec2 -[DVTSourceTextView setSelectedRanges:affinity:stillSelecting:] + 360
13  com.apple.dt.DVTKit             0x0000000105c87f78 -[DVTCompletingTextView setSelectedRange:] + 254
14  com.apple.dt.DVTKit             0x0000000105bbc780 -[DVTSourceTextView setSelectedRange:] + 52
15  com.apple.Foundation            0x00007fff8c877715 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 1049
16  com.apple.Foundation            0x00007fff8c9e7f53 _NSSetRangeValueAndNotify + 286
17  com.apple.dt.IDE.IDESourceEditor    0x0000000115249ac6 -[IDESourceCodeEditor navigateToAnnotationWithRepresentedObject:wantsIndicatorAnimation:exploreAnnotationRepresentedObject:] + 1547
18  com.apple.dt.IDEKit             0x00000001068deddb __332-[IDEEditorContext _notifyDelegateAndOpenNavigableItem:withContentsURL:documentExtensionIdentifier:locationToSelect:annotationRepresentedObject:stateDictionary:annotationWantsIndicatorAnimation:exploreAnnotationRepresentedObject:highlightSelection:alwaysReplaceExistingNavigableItem:skipSubDocumentNavigationUnlessEditorIsReplaced:]_block_invoke.1317 + 953
19  com.apple.dt.IDEKit             0x00000001068dd539 -[IDEEditorContext _notifyDelegateAndOpenNavigableItem:withContentsURL:documentExtensionIdentifier:locationToSelect:annotationRepresentedObject:stateDictionary:annotationWantsIndicatorAnimation:exploreAnnotationRepresentedObject:highlightSelection:alwaysReplaceExistingNavigableItem:skipSubDocumentNavigationUnlessEditorIsReplaced:] + 2362
20  com.apple.dt.IDEKit             0x00000001068dfa0c -[IDEEditorContext _notifyDelegateAndOpenEditorOpenSpecifier:updateHistory:] + 1266
21  com.apple.dt.IDEKit             0x00000001068d6f69 -[IDEEditorContext _openEditorOpenSpecifier:updateHistory:] + 383
22  com.apple.dt.IDEKit             0x00000001068d72af -[IDEEditorContext openEditorOpenSpecifier:] + 251
23  com.apple.dt.IDEKit             0x0000000106d08bf3 -[IDEEditorModeViewController openEditorOpenSpecifier:editorContext:] + 41
24  com.apple.dt.IDEKit             0x000000010694ce6e -[IDEEditorArea _openEditorOpenSpecifier:editorContext:takeFocus:] + 251
25  com.apple.dt.IDEKit             0x000000010693ab62 __108+[IDEEditorCoordinator _doOpenEditorOpenSpecifier:forWorkspaceTabController:editorContext:target:takeFocus:]_block_invoke + 173
26  com.apple.dt.IDEKit             0x000000010693a7b6 +[IDEEditorCoordinator _doOpenWithWorkspaceTabController:editorContext:target:allowFallback:documentURL:usingBlock:] + 1752
27  com.apple.dt.IDEKit             0x000000010693a9f6 +[IDEEditorCoordinator _doOpenEditorOpenSpecifier:forWorkspaceTabController:editorContext:target:takeFocus:] + 478

**Comment by leiyantianji** [comment]
[崩溃2.txt](https://github.com/keepyounger/HighlightSelectedString/files/188954/2.txt)
😭，上个崩溃还在comment，这个就来了。在断点调试ing，不知道怎么就崩了

**Comment by keepyounger** [comment]
我看来看去 只有
1 com.lixy.HighlightSelectedString 0x000000011341250e -[HighlightSelectedString selectionDidChange:] + 155 (HighlightSelectedString.m:245)
但是 对应代码是  245行 if (self.sourceTextView != textView) { 这句没理由崩溃啊

能具体描述一下重现步骤吗？

**Comment by keepyounger** [comment]
当时这个插件是设置情况是怎么样的 选中 symbols only了吗

**Comment by leiyantianji** [comment]
默认的配置，应该没选吧。不好重现的，反正今天动不动就崩。只好忍痛暂时卸载了，会不会是和其他有冲突呢？
![2016-03-25 12 16 06](https://cloud.githubusercontent.com/assets/12756236/14037836/8054dca0-f283-11e5-8fba-8bade78aa602.png)

**Comment by keepyounger** [comment]
Fuzzy和KSHObjc我没装，其他的我也装了啊，对了XCode7.3优化了代码补全功能，Fuzzy在7.3上好像报错

**Comment by keepyounger** [comment]
你也可以打开我的插件工程  然后执行 然后可以看看崩溃日志

**Comment by leiyantianji** [comment]
咦，难道是fuzzy的原因。刚刚下了最新的，编译失败(以前都是alcatraz安装插件的)。
我qq：245034483，如果可以麻烦你加一下😊，github聊的好费劲。哈哈

下面是你的部分日志

2016-03-25 13:34:04.125 Xcode[12358:748746] WARNING: Failed to load plugin at path: "/Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin/Contents/MacOS/FuzzyAutocomplete, 265): Symbol not found: _OBJC_CLASS_$_DVTTextCompletionInlinePreviewController
  Referenced from: /Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin/Contents/MacOS/FuzzyAutocomplete
  Expected in: /Applications/Xcode.app/Contents/MacOS/../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
 in /Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin/Contents/MacOS/FuzzyAutocomplete" UserInfo={NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin/Contents/MacOS/FuzzyAutocomplete, NSDebugDescription=dlopen(/Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin/Contents/MacOS/FuzzyAutocomplete, 265): Symbol not found: _OBJC_CLASS_$_DVTTextCompletionInlinePreviewController
  Referenced from: /Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin/Contents/MacOS/FuzzyAutocomplete
  Expected in: /Applications/Xcode.app/Contents/MacOS/../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
 in /Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin/Contents/MacOS/FuzzyAutocomplete, NSBundlePath=/Users/leiyan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin, NSLocalizedDescription=The bundle “FuzzyAutocomplete” couldn’t be loaded.}
2016-03-25 13:34:04.134 Xcode[12358:749044] Updating Repo: /Users/leiyan/Library/Application Support/Alcatraz/Plug-ins/Alcatraz
git version 2.6.4 (Apple Git-63)
2016-03-25 13:34:09.946 Xcode[12358:748746] Git fetch output: 
2016-03-25 13:34:09.956 Xcode[12358:748746] Git reset output: HEAD is now at 06f7f99 updated install script for version 1.1.17

**Comment by keepyounger** [comment]
恩 恩 删除了Fuzzy 还崩溃吗？
 如果不崩溃了 我就把这个issue关了。

**Comment by why19910522** [comment]
我今天也遇到这个问题了，我用的Xcode7.2，上午还好好的，下午突然就开始了，无法做任何操作，一点击就崩，

**Comment by TSEL0** [comment]
我是更新了7.3就崩 一开始没事 后来突然就一直崩..

**Comment by leiyantianji** [comment]
额，抱歉啊。因为撸代码多，Fuzzy的需求率更大点，所以删掉Highlight了。楼主抱歉啊。。。。

**Comment by keepyounger** [comment]
@why19910522  @BrookZero 你们也安装Fuzzy了？如果安装了 试试删除掉Fuzzy，看看还崩溃吗

**Comment by why19910522** [comment]
没啊，我就这么多插件
![snip20160325_26](https://cloud.githubusercontent.com/assets/13136383/14041256/ff4e45fc-f2a9-11e5-9ca2-9b68010c7c04.png)

**Comment by willey-l** [comment]
Process:               Xcode [5387]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.3 (10183.3)
Build Info:            IDEFrameworks-10183003000000000~2
App Item ID:           497799835
App External ID:       816750016
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [5387]
User ID:               501

PlugIn Path:             /Users/USER/Library/Application Support/Developer/*/HighlightSelectedString
PlugIn Identifier:       com.lixy.HighlightSelectedString
PlugIn Version:          2.1.1 (1)

Date/Time:             2016-03-25 16:52:05.408 +0800
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        0C367617-7E18-BC50-FC98-9E981E605BE4

Time Awake Since Boot: 10000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x20:
--> 
    __TEXT                 000000010a9b9000-000000010a9bd000 [   16K] r-x/rwx SM=COW  /Applications/Xcode.app/Contents/MacOS/Xcode

Application Specific Information:
ProductBuildVersion: 7D175

Global Trace Buffer (reverse chronological seconds):
7750.885529  CFNetwork                  0x00007fff89ced447 TCP Conn 0x7ff68e734d50 SSL Handshake DONE
7751.601881  CFNetwork                  0x00007fff89ced323 TCP Conn 0x7ff68e734d50 starting SSL negotiation
7751.602378  CFNetwork                  0x00007fff89cebced TCP Conn 0x7ff68e734d50 complete. fd: 16, err: 0
7751.602579  CFNetwork                  0x00007fff89d7a5c7 TCP Conn 0x7ff68e734d50 event 1. err: 0
7752.040341  CFNetwork                  0x00007fff89ceafbf TCP Conn 0x7ff68e734d50 started
7752.139571  CFNetwork                  0x00007fff89caec42 Creating default cookie storage with process/bundle identifier
7752.139571  CFNetwork                  0x00007fff89caebda Faulting in CFHTTPCookieStorage singleton
7752.139581  CFNetwork                  0x00007fff89caea69 Faulting in NSHTTPCookieStorage singleton
7752.141684  CFNetwork                  0x00007fff89dac510 NSURLConnection finished with error - code -1100

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib                 0x00007fff86117ec1 objc_retain + 33
1   com.lixy.HighlightSelectedString    0x000000011446450e -[HighlightSelectedString selectionDidChange:] + 155 (HighlightSelectedString.m:245)
2   com.apple.CoreFoundation        0x00007fff8fe36bbc **CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER** + 12
3   com.apple.CoreFoundation        0x00007fff8fe36b4f ___CFXRegistrationPost_block_invoke + 63
4   com.apple.CoreFoundation        0x00007fff8fe36ac7 _CFXRegistrationPost + 407
5   com.apple.CoreFoundation        0x00007fff8fe36832 ___CFXNotificationPost_block_invoke + 50
6   com.apple.CoreFoundation        0x00007fff8fdf35e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
7   com.apple.CoreFoundation        0x00007fff8fdf2835 _CFXNotificationPost + 693
8   com.apple.Foundation            0x00007fff911e6fda -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
9   com.apple.dt.DVTFoundation      0x000000010abb50ef -[NSNotificationCenter(DVTNSNotificationCenterAdditions) _dvt_postNotificationName:object:userInfo:] + 831
10  com.apple.AppKit                0x00007fff8b16ad18 -[NSTextView(NSSharing) setSelectedRanges:affinity:stillSelecting:] + 7403
11  com.apple.dt.DVTKit             0x000000010b329e23 -[DVTCompletingTextView setSelectedRanges:affinity:stillSelecting:] + 201
12  com.apple.dt.DVTKit             0x000000010b25eec2 -[DVTSourceTextView setSelectedRanges:affinity:stillSelecting:] + 360
13  com.apple.AppKit                0x00007fff8b46840a -[NSTextView mouseDown:] + 12266
14  com.apple.dt.DVTKit             0x000000010b32ada3 -[DVTCompletingTextView mouseDown:] + 406
15  com.apple.dt.DVTKit             0x000000010b26649a -[DVTSourceTextView mouseDown:] + 1152
16  com.apple.AppKit                0x00007fff8b843bf5 -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 62
17  com.apple.AppKit                0x00007fff8b84644d -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
18  com.apple.AppKit                0x00007fff8b996e9b _NSGestureRecognizerUpdate + 2630
19  com.apple.AppKit                0x00007fff8b84363f -[NSWindow _sendEventToGestureRecognizers:requireAcceptsFirstMouse:] + 2755
20  com.apple.AppKit                0x00007fff8b285620 -[NSWindow sendEvent:] + 488
21  com.apple.dt.IDEKit             0x000000010c031d86 -[IDEWorkspaceWindow sendEvent:] + 155
22  com.apple.AppKit                0x00007fff8b205b3c -[NSApplication sendEvent:] + 2540
23  com.apple.dt.IDEKit             0x000000010c0727f2 -[IDEApplication sendEvent:] + 894
24  com.apple.AppKit                0x00007fff8b06cef6 -[NSApplication run] + 796
25  com.apple.AppKit                0x00007fff8b03646c NSApplicationMain + 1176
26  com.apple.dt.Xcode              0x000000010a9ba39b 0x10a9b9000 + 5019
27  libdyld.dylib                   0x00007fff94b9d5ad start + 1

**Comment by keepyounger** [comment]
@leiyantianji 我要的结果 我的意思是 是不是和 Fuzzy冲突，不是删掉那个的问题

**Comment by willey-l** [comment]
我的也崩了

**Comment by leiyantianji** [comment]
@keepyounger 恩恩，我晚上试试删掉Fuzzy，看会不会崩。我的意思是，我暂时不能帮忙测是不是和Fuzzy冲突。需要稍晚点才能给你结果。抱歉，让你误解了

**Comment by leewi9** [comment]
今天崩了几十次了。
![snip20160325_9](https://cloud.githubusercontent.com/assets/10832544/14041840/a49a65d6-f2af-11e5-8d6a-07c0789a4b78.png)

**Comment by keepyounger** [comment]
你们可以先用之前的版本 等我找到问题了 再更新

**Comment by keepyounger** [comment]
@leewi9  我一次都没遇到过 不好定位问题所在

**Comment by keepyounger** [comment]
我修改了一些代码，有时间的朋友可以试试看，还崩溃不，谢谢！

**Comment by erickyim** [comment]
请参考：

![screen shot 2016-03-29 at 10 31 10](https://cloud.githubusercontent.com/assets/8186665/14096593/abbc74c2-f59c-11e5-957f-ec3dfe476780.png)

``` objc
@property (nonatomic, unsafe_unretained) NSTextView *sourceTextView;
```

`NSTextView`：有个说明`NS_AUTOMATED_REFCOUNT_WEAK_UNAVAILABLE`

**Comment by keepyounger** [comment]
@cyvoit 谢谢！我觉得也是这个引用的问题，我把判断删除了，不知道还会不会崩溃。

**Comment by why19910522** [comment]
好像是没事儿了，我刚测试了下没有崩溃。

**Comment by keepyounger** [comment]
@why19910522 谢谢！有崩溃及时反馈

**Comment by why19910522** [comment]
@keepyounger OK

**Comment by Legoless** [comment]
It would be greatly appreciated if you guys debated in English, so others can understand too. The plugin causes crashes for me too and seems similar to this issue.

**Comment by keepyounger** [comment]
@Legoless  You can try the latest version.

**Comment by leewi9** [comment]
@Legoless Hi, you can try this one, it won't crash.
https://github.com/chiahsien/AutoHighlightSymbol

**Comment by boai** [comment]
我的也是一直崩。。。烦死了！

**Comment by keepyounger** [comment]
@boai 试试最新版本
