### ISSUE TITLE
Doesn't work with Xcode 7 beta 3 (7a152u)

### ISSUE THREAD

**Issue by MarcVienna** [keepyounger/HighlightSelectedString#7]
Xcode 6.4 works fine.

**Comment by keepyounger** [comment]
@MarcVienna  It can work with both Xcode release version and Xcode beta version now.

**Comment by MarcVienna** [comment]
Works. Thanks.

**Comment by MarcVienna** [comment]
It works in Xcode 7 now - but it doesn't in Xcode 6.4.
Perhaps I should download the old version again...

**Comment by keepyounger** [comment]
I'm sorry.  It can work with all versions by using python script, if your MAC has only one Xcode. If I don't use python script, I must update it when Xcode update. The problem is your MAC has tow Xcodes. I try use python script make it works with two Xcodes, but it looks like failed. I have to give up python script now. Wait a moment, I will update it.

**Comment by keepyounger** [comment]
I have updated it. By the way, my English is not very good, please understand.

**Comment by MarcVienna** [comment]
Doesn't work with Xcode 7 GM (7a218) 
Doesn't work with Xcode 7.1 beta (7b60)

I have 3 Xcode versions now: 6.4, 7 GM, 7.1beta.

**Comment by MarcVienna** [comment]
Doesn't work with Xcode 7 GM (7a218)
